# .scrutinizer.yml
checks:
  php: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    memcached: true
    redis: true
    php:
      version: 7.3
      pecl_extensions:
        - igbinary
        - redis
        - memcached
        - apcu
      ini:
        apc.enable: 1
        apc.enable_cli: 1
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=.soupmix_coverage.xml'
        coverage:
          file: '.soupmix_coverage.xml'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"