# .scrutinizer.yml
checks:
  php: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    php:
      version: 7.3
      pecl_extensions:
        - igbinary
        - redis
        - memcached
        - apcu
      ini:
        apc.enable_cli: "1"
  services:
    redis: 5
    memcahced: 1.6
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=.soupmix_coverage'
        coverage:
          file: '.soupmix_coverage'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"